name: auth_management
description: Collection of auth service with advanced controlling system.
version: 3.2.6
repository: https://github.com/P-YMR/flutter_auth_management.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_entity: ^1.2.7
  object_modifier: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0